### ISSUE TITLE
Minimum coverage

### ISSUE THREAD

**Issue by rania-o** [novoalab/EpiNano#115]
Hello,

I used Epinano_error to detect modifications in my sample.
I wanted to know, if the 30x minimum coverage you mentioned, is the number of reads aligned to the reference (i.e. modified and unmodified reads that map to a position) or is it the minimum number of reads that must be modified to detect a modified base (i.e. a position covered with 70 reads, and 30 of them are modified, so you assume that this position is modified) ? ?
if it's the number of reads aligned to the reference (general coverage of mapping), do you consider a minimum number of reads to assume that a position is modified or for example 1 modified read is enough ?

Thank you,
Rania

**Comment by Huanle** [comment]
Hi @rania-o ,

Sorry for my late reply.
`30x` minimum coverage means the total number of reads mapped to a given site, aka, it is the same as sequencing depth.
It is an arbitrary number up to your choice.
I can not say how many modified reads are enough to be detected. Because the detection depends on the contrast between your samples involved in the comparison. It also depends on the type of modifications that are being studied. 
Hope this makes sense to you. 
Please let me know if you more questions.

**Comment by rania-o** [comment]
Thank you @Huanle, it is more clear now.
