### ISSUE TITLE
error runing epinano_variants.py

### ISSUE THREAD

**Issue by CharlotteAnne** [novoalab/EpiNano#126]
Hi,

When trying to run Epinano v1.2.0 variants.py with the following command:

```
python3 Epinano_Variants.py -R /bucket/LuscombeU/common/Breakpoints/Genomes/OSKA2016v1.9.fa \
-b /home/c/c-capitanchik/flash/osaka_direct_rna/MOP2/mop_preprocess/osdirna_results/alignment/pass_s.bam \
-s /bucket/.deigo/LuscombeU/live/charlottecapitanchik/software/jvarkit/dist/sam2tsv.jar \
-n 8 \
-T g
```

I get the following error: 

```
/home/c/c-capitanchik/flash/osaka_direct_rna/MOP2/mop_preprocess/osdirna_results/alignment/pass_s_TMP_ already exists, will overwrite it
Process Process-2:
Traceback (most recent call last):
  File "/bucket/LuscombeU/live/charlottecapitanchik/software/miniconda3/envs/bioinf/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/bucket/LuscombeU/live/charlottecapitanchik/software/miniconda3/envs/bioinf/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "Epinano_Variants.py", line 44, in split_tsv_for_per_site_var_freq
    head = next(tsv)
StopIteration
```

-- please could you advise what might be wrong? Thank you for your help!

Charlotte

**Comment by liuqianhn** [comment]
Hi, I have a similar error. May I know how to solve it? 

Meanwhile, may I know why your `sam2tsv.jar` is not `EpiNano/misc/sam2tsv.jar` @CharlotteAnne  ?

**Comment by enovoa** [comment]
Dear @liuqianhn and @CharlotteAnne, 

You should use the `sam2tsv.jar` version that is provided as part of EpiNano. Please use the .jar provided, rather than: `/bucket/.deigo/LuscombeU/live/charlottecapitanchik/software/jvarkit/dist/sam2tsv.jar`

If you still have issues, I would recommend to use the EpiNano Dockerfile that you can find here: https://github.com/novoalab/EpiNano/tree/master/dockerfile 

Finally, if you are still experiencing issues, you  may use EpiNano 1.1.1 that is distributed as part of MoP2 (https://github.com/biocorecrg/MOP2) 

Hope this helps!
Eva

**Comment by liuqianhn** [comment]
Hi @enovoa Thank you very much for your help. I can run the docker. I also have several questions to run epinano
1. What is output of `Epinano_Variants.py`?
2. What is output of `Epinano_Current.sh`?
3. What is output of `Epinano_DiffErr.R`?

Meanwhile, when I run `Epinano_Current.sh`, I only see `*.bam.forward.reads` and empty `.eventalign.tsv.gz`. May I know what is wrong? There is no error message when I run docker. Thanks.

**Comment by ixeft** [comment]
The error come from the fact that sam2tsv.jar has change is command line usage, now it takes "-R" instead of "-r" for reference file.

**Comment by enovoa** [comment]
Hello, did you try the sam2tsv.jar that is included as part of the EpiNano repo? It seems you are using /bucket/.deigo/LuscombeU/live/charlottecapitanchik/software/jvarkit/dist/sam2tsv.jar  

Regarding the dockerfile - can you please try with the demo/test data included in the repo? Thanks!

**Comment by liu2005678** [comment]
Epinano_Variants only output one single feature table: samples.per.site.var.csv. The other "sample.per_site.5mer.csv" is not generated !!!
I used the provied fast5 and fastq file to train my own SVM mode. Instead of DRACH, I'd like to train a UVAAR motif. 
I download the fast5 files (RNA081120181 and RNA081120182) and its corresponding fastq files, mapped with minimap2 as suggested. However, starting with Epinano, I entered troubles. The Epinano_Variants command was listed as below:
python ~/programs/EpiNano/Epinano_Variants.py -n 30 -R ~/programs/EpiNano/Reference_sequences/cc.fasta -b 20181.bam -s ~/programs/EpiNano/misc/sam2tsv.jar --type t

**Comment by Madhurananda** [comment]
Hi @CharlotteAnne @liuqianhn @enovoa @ixeft 

I am using the latest Epinano 1.2 and also experienced the same issue: Process Process-2:

This usually happens when an empty job is provided to the multiprocessing, I believe. At line 99/103 inside Epinano_Variants.py; there is a command:
f"samtools view -h -F 3860 {bam_file} | java -jar  {sam2tsv} -r {reference_file} "\
			f" | {awk_forward_strand}"

This will only return results when the Anaconda environment has the samtools installed, as required. I didn't have it installed initially, but I successfully generated the CSV files later. 

I hope this helps.

**Comment by Huanle** [comment]
> Hi @enovoa Thank you very much for your help. I can run the docker. I also have several questions to run epinano
> 
> 1. What is output of `Epinano_Variants.py`?
> 2. What is output of `Epinano_Current.sh`?
> 3. What is output of `Epinano_DiffErr.R`?
> 
> Meanwhile, when I run `Epinano_Current.sh`, I only see `*.bam.forward.reads` and empty `.eventalign.tsv.gz`. May I know what is wrong? There is no error message when I run docker. Thanks.

Hi @liuqianhn,

Sorry for the late chime in.
There is a [wiki](https://github.com/novoalab/EpiNano/wiki/EpiNano-wiki) that can help.

**Comment by Huanle** [comment]
> The error come from the fact that sam2tsv.jar has change his command line usage, now it takes "-R" instead of "-r" for reference file. Unfortunately, EpiNano fail after the sam2tsv step, when trying to use the output of sam2tsv

Hi @ixeft ,

The sam2tsv.jar in the **misc/** folder should work. 
Let me know if it works and sorry for the late reply.

Huanle
